"""Reproducible train/validation/test split construction and manifests."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np

from data import smarthome
from data.datasets import GENERATOR_VERSION, GridDataset, augment_example, generate_example

_SPLITS = ("train", "validation", "test")


def _digest(*parts: bytes | str) -> str:
    h = hashlib.sha256()
    for part in parts:
        b = part.encode("utf-8") if isinstance(part, str) else part
        h.update(len(b).to_bytes(8, "little")); h.update(b)
    return h.hexdigest()


def _array_bytes(a: np.ndarray) -> bytes:
    return np.ascontiguousarray(a, dtype="<i8").tobytes()


def example_fingerprint(task: str, x: np.ndarray, y: np.ndarray, h: int, w: int) -> str:
    return _digest(task, f"{h}x{w}", _array_bytes(x), _array_bytes(y))


def _smart_home_code_partition(seed: int) -> dict[str, np.ndarray]:
    """Stable 52/6/6 partition of all 64 exact smart-home states."""
    ranked = sorted(
        range(smarthome.NUM_STATES),
        key=lambda code: _digest("smarthome-state-split", str(seed), str(code)),
    )
    return {
        "train": np.asarray(ranked[:52], dtype=np.int64),
        "validation": np.asarray(ranked[52:58], dtype=np.int64),
        "test": np.asarray(ranked[58:], dtype=np.int64),
    }


def _difficulty_summary(metadata: list[dict[str, Any]]) -> dict[str, Any]:
    values: dict[str, list[Any]] = {}
    for row in metadata:
        for key, value in row.get("difficulty", {}).items():
            values.setdefault(key, []).append(value)
    out: dict[str, Any] = {}
    for key, vals in values.items():
        if vals and all(isinstance(v, (int, float, np.integer, np.floating, bool)) for v in vals):
            numeric = np.asarray(vals, dtype=np.float64)
            summary: dict[str, Any] = {
                "min": float(numeric.min()),
                "max": float(numeric.max()),
                "mean": float(numeric.mean()),
            }
            unique, counts = np.unique(np.asarray(vals), return_counts=True)
            if len(unique) <= 64:
                summary["counts"] = {
                    str(v.item() if hasattr(v, "item") else v): int(c)
                    for v, c in zip(unique, counts)
                }
            out[key] = summary
        else:
            counts: dict[str, int] = {}
            for v in vals:
                counts[str(v)] = counts.get(str(v), 0) + 1
            out[key] = {"counts": counts}
    return out


def _spatial_shape(task: str, kwargs: dict[str, Any]) -> tuple[int, int]:
    if task == "sudoku":
        side = int(kwargs.get("box", 3)) ** 2
        return side, side
    if task == "arc":
        return int(kwargs["canvas_h"]), int(kwargs["canvas_w"])
    if task == "smarthome":
        return 1, smarthome.SEQ_LEN
    return int(kwargs["height"]), int(kwargs["width"])


def _content_masks(task: str, x: np.ndarray, y: np.ndarray, pad_token: int | None):
    if task == "arc":
        assert pad_token is not None
        return x != pad_token, y != pad_token
    if task == "smarthome":
        return x != smarthome.PAD, np.ones(y.shape, dtype=bool)
    return np.ones(x.shape, dtype=bool), np.ones(y.shape, dtype=bool)


def _generate_base(
    task: str,
    rng: np.random.Generator,
    kwargs: dict[str, Any],
    *,
    smart_codes: np.ndarray | None = None,
):
    if task != "smarthome":
        return generate_example(task, rng, **kwargs)
    if smart_codes is None:
        raise RuntimeError("smart-home grouped split requires an allowed state-code partition")
    x, y = smarthome.generate_pair(rng, allowed_codes=smart_codes)
    return x, y, 1, smarthome.SEQ_LEN, {
        "difficulty": {
            "action": int(y[0]),
            "nonpad_sensor_tokens": int((x != smarthome.PAD).sum()),
        },
        "state_code": smarthome.state_code({
            feat: int((int(x[i]) - 1 - 2 * i)) for i, feat in enumerate(smarthome.FEATURES)
        }),
    }


def build_reproducible_splits(
    task: str,
    sizes: dict[str, int],
    seed: int,
    *,
    generator_kwargs: dict[str, Any],
    task_scope: str,
    official_benchmark: bool,
    max_duplicate_retries: int = 1024,
    forbidden_fingerprints: frozenset[str] | None = None,
    require_unique_examples: bool = False,
    grouping: str = "exact",
    require_unique_groups: bool = False,
) -> tuple[dict[str, GridDataset], dict[str, Any]]:
    """Build grouped splits with independent RNG streams and a reproducible manifest.

    A base ``group_id`` is computed before augmentation. If an exact base problem
    is ever regenerated by a different split, that draw is rejected. All derived
    augmentations therefore remain with their base group. The finite smart-home
    state universe is pre-partitioned explicitly instead of relying on rejection.
    Opt-in Sudoku4 isomorphism grouping replaces group IDs with input-only orbit
    keys. Pass ancestor orbit keys in forbidden_fingerprints as well as existing
    exact hashes; legacy exact-only manifests do not imply symmetry exclusions.
    require_unique_groups retains at most one representative per group globally.
    Legacy defaults and their generated manifests remain unchanged.
    """
    from data.sudoku_symmetry import POLICY, sudoku4_orbit_key
    if grouping not in ("exact", POLICY):
        raise ValueError("unknown split grouping policy")
    if type(require_unique_groups) is not bool:
        raise TypeError("require_unique_groups must be bool")
    if grouping == POLICY and (task != "sudoku" or generator_kwargs.get("box") != 2):
        raise ValueError("Sudoku4 isomorphism grouping requires Sudoku with box=2")
    accepted_groups: set[str] = set()
    forbidden = frozenset(forbidden_fingerprints or ())
    if any(not isinstance(fp, str) or len(fp) != 64 or any(c not in "0123456789abcdef" for c in fp) for fp in forbidden):
        raise ValueError("forbidden fingerprints must be SHA-256 content hashes")
    seen_final: set[str] = set()
    requested = {name: int(sizes.get(name, 0)) for name in _SPLITS}
    if any(v < 0 for v in requested.values()):
        raise ValueError("split sizes must be non-negative")
    if not isinstance(seed, int) or isinstance(seed, bool):
        raise TypeError("seed must be an integer")

    root = np.random.SeedSequence(seed)
    children = root.spawn(6)
    streams = {
        split: {
            "generation": children[2 * i],
            "augmentation": children[2 * i + 1],
        }
        for i, split in enumerate(_SPLITS)
    }
    smart_partition = _smart_home_code_partition(seed) if task == "smarthome" else None

    group_owner: dict[str, str] = {}
    split_rows: dict[str, list[dict[str, Any]]] = {s: [] for s in _SPLITS}
    split_arrays: dict[str, tuple[list[np.ndarray], list[np.ndarray]]] = {
        s: ([], []) for s in _SPLITS
    }

    for split in _SPLITS:
        gen_rng = np.random.default_rng(streams[split]["generation"])
        aug_rng = np.random.default_rng(streams[split]["augmentation"])
        xs, ys = split_arrays[split]
        retries = 0
        while len(xs) < requested[split]:
            x0, y0, h, w, meta = _generate_base(
                task, gen_rng, generator_kwargs,
                smart_codes=None if smart_partition is None else smart_partition[split],
            )
            base_fp = example_fingerprint(task, x0, y0, h, w)
            group_id = sudoku4_orbit_key(x0) if grouping == POLICY else base_fp
            owner = group_owner.get(group_id)
            if (base_fp in forbidden or group_id in forbidden or
                    (owner is not None and owner != split) or
                    (require_unique_groups and group_id in accepted_groups)):
                retries += 1
                if retries > max_duplicate_retries:
                    raise RuntimeError(
                        f"could not obtain a non-leaking {split} base group after {retries} duplicate retries"
                    )
                continue
            group_owner.setdefault(group_id, split)
            # height/width are already the authoritative generated dimensions passed
            # positionally. Do not pass duplicate task config names again.
            aug_kwargs = {
                k: v for k, v in generator_kwargs.items() if k not in {"height", "width"}
            }
            x, y = augment_example(task, x0, y0, h, w, aug_rng, **aug_kwargs)
            if grouping == POLICY and sudoku4_orbit_key(x) != group_id:
                raise RuntimeError("augmentation escaped its declared Sudoku4 orbit")
            final_fp = example_fingerprint(task, x, y, h, w)
            if final_fp in forbidden or (require_unique_examples and final_fp in seen_final):
                retries += 1
                if retries > max_duplicate_retries:
                    raise RuntimeError("could not obtain ancestor-disjoint unique examples")
                continue
            seen_final.add(final_fp)
            accepted_groups.add(group_id)
            ordinal = len(xs)
            stable_id = _digest(
                GENERATOR_VERSION, task, str(seed), split, str(ordinal), group_id, final_fp
            )[:24]
            xs.append(np.asarray(x, dtype=np.int64))
            ys.append(np.asarray(y, dtype=np.int64))
            split_rows[split].append({
                "id": stable_id,
                "group_id": group_id,
                "fingerprint": final_fp,
                "difficulty": meta.get("difficulty", {}),
                "metadata": {k: v for k, v in meta.items() if k != "difficulty"},
            })

    datasets: dict[str, GridDataset] = {}
    num_tokens = int(generator_kwargs["num_tokens"])
    pad_token = generator_kwargs.get("pad_token", None)
    pad_token = None if pad_token is None else int(pad_token)
    h, w = _spatial_shape(task, generator_kwargs)
    expected_len = int(generator_kwargs.get("seq_len", h * w))
    if expected_len != h * w:
        raise ValueError("generator kwargs seq_len disagrees with spatial contract")

    for split in _SPLITS:
        xs, ys = split_arrays[split]
        if xs:
            x = np.stack(xs); y = np.stack(ys)
        else:
            x = np.empty((0, h * w), dtype=np.int64); y = np.empty_like(x)
        im, tm = _content_masks(task, x, y, pad_token)
        rows = split_rows[split]
        datasets[split] = GridDataset(
            x, y, h, w, task=task, num_tokens=num_tokens, pad_token=pad_token,
            input_mask=im, target_mask=tm,
            ids=[r["id"] for r in rows],
            group_ids=[r["group_id"] for r in rows],
            metadata=[{"difficulty": r["difficulty"], **r["metadata"]} for r in rows],
        )

    group_sets = {s: set(datasets[s].group_ids) for s in _SPLITS}
    fp_sets = {s: {r["fingerprint"] for r in split_rows[s]} for s in _SPLITS}
    cross_group = {
        "train_validation": len(group_sets["train"] & group_sets["validation"]),
        "train_test": len(group_sets["train"] & group_sets["test"]),
        "validation_test": len(group_sets["validation"] & group_sets["test"]),
    }
    cross_exact = {
        "train_validation": len(fp_sets["train"] & fp_sets["validation"]),
        "train_test": len(fp_sets["train"] & fp_sets["test"]),
        "validation_test": len(fp_sets["validation"] & fp_sets["test"]),
    }
    if any(cross_group.values()) or any(cross_exact.values()):
        raise RuntimeError(f"cross-split duplicate audit failed: groups={cross_group}, exact={cross_exact}")

    manifest = {
        "schema_version": 1,
        "generator_version": GENERATOR_VERSION,
        "task": task,
        "task_scope": task_scope,
        "official_benchmark": bool(official_benchmark),
        "seed": seed,
        "split_policy": {
            "rng": "NumPy SeedSequence with separate generation and augmentation child streams per split",
            "grouping": "group_id is computed from the unaugmented base pair before augmentation",
            "augmentation_leakage": "all augmentations remain in the owning base split",
            "smarthome": "finite 64-state universe is deterministically partitioned 52/6/6",
        },
        "rng_streams": {
            s: {
                "generation_spawn_key": list(streams[s]["generation"].spawn_key),
                "augmentation_spawn_key": list(streams[s]["augmentation"].spawn_key),
            }
            for s in _SPLITS
        },
        "generator_kwargs": generator_kwargs,
        "splits": {
            s: {
                "count": len(split_rows[s]),
                "difficulty_distribution": _difficulty_summary(
                    [{"difficulty": r["difficulty"]} for r in split_rows[s]]
                ),
                "examples": split_rows[s],
            }
            for s in _SPLITS
        },
        "duplicate_audit": {
            "cross_split_group_overlap": cross_group,
            "cross_split_exact_overlap": cross_exact,
            "within_split_duplicate_groups": {
                s: len(datasets[s].group_ids) - len(group_sets[s]) for s in _SPLITS
            },
            "within_split_exact_duplicates": {
                s: len(split_rows[s]) - len(fp_sets[s]) for s in _SPLITS
            },
        },
    }
    if forbidden_fingerprints is not None or require_unique_examples:
        manifest["external_exclusion"] = {
            "fingerprint_count": len(forbidden),
            "sorted_fingerprints_sha256": hashlib.sha256("\n".join(sorted(forbidden)).encode()).hexdigest(),
            "require_unique_examples": bool(require_unique_examples),
            "scope": "exact final fingerprints and pre-augmentation groups",
        }
    if grouping != "exact" or require_unique_groups:
        manifest["split_policy"].update(
            grouping=grouping, require_unique_groups=require_unique_groups,
            equivalence_scope=("input-only 4x4 Sudoku isomorphism; not arbitrary task equivalence"
                               if grouping == POLICY else "exact unaugmented input/target pairs"))
    return datasets, manifest


def write_manifest(path: str | Path, manifest: dict[str, Any]) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
