"""Sudoku generation, solving, and validation.

Milestone 03 makes the NumPy contract strict: a Sudoku grid must have exactly the
shape implied by ``box``, integral values in ``0..N`` (or ``1..N`` when solved),
and no contradictory non-zero clues.  Invalid puzzles are never passed into the
bit-mask solver.

Completed boards are generated by randomized MRV/backtracking from an empty grid
by default.  This removes the old construction restriction in which every board
was obtained only by symmetry transforms of one canonical completed solution.
"""
from __future__ import annotations

import numpy as np


def grid_size(box: int) -> int:
    if not isinstance(box, (int, np.integer)) or isinstance(box, (bool, np.bool_)) or int(box) <= 0:
        raise ValueError(f"box must be a positive integer, got {box!r}")
    return int(box) * int(box)


def _coerce_grid(grid: np.ndarray, box: int, *, solved: bool = False) -> np.ndarray | None:
    """Return a checked int64 view/copy, or ``None`` for malformed input."""
    try:
        n = grid_size(box)
        arr = np.asarray(grid)
    except Exception:
        return None
    if arr.shape != (n, n):
        return None
    if arr.dtype.kind not in "iu":
        return None
    lo = 1 if solved else 0
    if arr.size and (int(arr.min()) < lo or int(arr.max()) > n):
        return None
    return arr.astype(np.int64, copy=False)


def _has_dup(values: np.ndarray) -> bool:
    nonzero = values[values != 0]
    return nonzero.size != np.unique(nonzero).size


def _groups_ok(grid: np.ndarray, box: int) -> bool:
    n = grid_size(box)
    for i in range(n):
        if _has_dup(grid[i, :]) or _has_dup(grid[:, i]):
            return False
    for br in range(box):
        for bc in range(box):
            block = grid[br * box : (br + 1) * box, bc * box : (bc + 1) * box]
            if _has_dup(block.reshape(-1)):
                return False
    return True


def is_valid_grid(grid: np.ndarray, box: int) -> bool:
    """True only for a well-formed, in-range, contradiction-free partial grid."""
    checked = _coerce_grid(grid, box, solved=False)
    return checked is not None and _groups_ok(checked, box)


def is_solved(grid: np.ndarray, box: int) -> bool:
    """True only for a well-formed complete Sudoku solution."""
    checked = _coerce_grid(grid, box, solved=True)
    return checked is not None and _groups_ok(checked, box)


def respects_clues(
    puzzle: np.ndarray, solution: np.ndarray, box: int | None = None
) -> bool:
    """True iff every non-zero clue is preserved and shapes/domains are sane."""
    p = np.asarray(puzzle)
    s = np.asarray(solution)
    if p.shape != s.shape or p.ndim != 2 or p.shape[0] != p.shape[1]:
        return False
    if p.dtype.kind not in "iu" or s.dtype.kind not in "iu":
        return False
    if box is not None:
        pc = _coerce_grid(p, box, solved=False)
        sc = _coerce_grid(s, box, solved=True)
        if pc is None or sc is None:
            return False
        p, s = pc, sc
    elif p.size and (int(p.min()) < 0 or int(s.min()) < 0):
        return False
    mask = p != 0
    return bool((s[mask] == p[mask]).all())


def _initial_masks(grid: np.ndarray, box: int):
    """Build solver masks after validation; returns rows, cols, boxes, empties."""
    n = grid_size(box)
    rows = [0] * n
    cols = [0] * n
    boxes = [0] * n
    empties: list[int] = []
    for r in range(n):
        for c in range(n):
            v = int(grid[r, c])
            if v:
                bit = 1 << (v - 1)
                b = (r // box) * box + (c // box)
                rows[r] |= bit
                cols[c] |= bit
                boxes[b] |= bit
            else:
                empties.append(r * n + c)
    return rows, cols, boxes, empties


def count_solutions(puzzle: np.ndarray, box: int, limit: int = 2) -> int:
    """Count solutions up to ``limit``; malformed/contradictory puzzles have 0."""
    if not isinstance(limit, (int, np.integer)) or int(limit) < 1:
        raise ValueError("limit must be a positive integer")
    checked = _coerce_grid(puzzle, box, solved=False)
    if checked is None or not _groups_ok(checked, box):
        return 0
    n = grid_size(box)
    full = (1 << n) - 1
    rows, cols, boxes, cells = _initial_masks(checked, box)
    count = 0

    def backtrack() -> bool:
        nonlocal count
        if not cells:
            count += 1
            return count >= int(limit)
        best_i, best_mask, best_n = -1, 0, n + 1
        for idx, cell in enumerate(cells):
            r, c = divmod(cell, n)
            b = (r // box) * box + (c // box)
            avail = full & ~(rows[r] | cols[c] | boxes[b])
            popcount = avail.bit_count()
            if popcount < best_n:
                best_i, best_mask, best_n = idx, avail, popcount
                if popcount <= 1:
                    break
        if best_n == 0:
            return False
        cell = cells.pop(best_i)
        r, c = divmod(cell, n)
        b = (r // box) * box + (c // box)
        mask = best_mask
        while mask:
            bit = mask & -mask
            mask ^= bit
            rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit
            if backtrack():
                rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit
                cells.insert(best_i, cell)
                return True
            rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit
        cells.insert(best_i, cell)
        return False

    backtrack()
    return count


def solve(puzzle: np.ndarray, box: int) -> np.ndarray | None:
    """Return one completion, or ``None`` for malformed/contradictory/unsolved input."""
    checked = _coerce_grid(puzzle, box, solved=False)
    if checked is None or not _groups_ok(checked, box):
        return None
    n = grid_size(box)
    full = (1 << n) - 1
    grid = checked.copy()
    rows, cols, boxes, empties = _initial_masks(grid, box)

    def backtrack() -> bool:
        if not empties:
            return True
        best_i, best_mask, best_n = -1, 0, n + 1
        for idx, cell in enumerate(empties):
            r, c = divmod(cell, n)
            b = (r // box) * box + (c // box)
            avail = full & ~(rows[r] | cols[c] | boxes[b])
            popcount = avail.bit_count()
            if popcount < best_n:
                best_i, best_mask, best_n = idx, avail, popcount
                if popcount <= 1:
                    break
        if best_n == 0:
            return False
        cell = empties.pop(best_i)
        r, c = divmod(cell, n)
        b = (r // box) * box + (c // box)
        mask = best_mask
        while mask:
            bit = mask & -mask
            mask ^= bit
            rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit
            grid[r, c] = bit.bit_length()
            if backtrack():
                return True
            rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit
            grid[r, c] = 0
        empties.insert(best_i, cell)
        return False

    return grid if backtrack() else None


def band_preserving_order(box: int, rng: np.random.Generator) -> list[int]:
    bands = list(rng.permutation(box))
    order: list[int] = []
    for band in bands:
        lines = list(rng.permutation(box))
        order.extend(int(band) * box + int(line) for line in lines)
    return order


def _canonical_symmetry_solution(box: int, rng: np.random.Generator) -> np.ndarray:
    """Legacy symmetry-family generator retained only for explicit experiments."""
    n = grid_size(box)
    def pattern(r: int, c: int) -> int:
        return (box * (r % box) + r // box + c) % n
    rows_order = band_preserving_order(box, rng)
    cols_order = band_preserving_order(box, rng)
    labels = rng.permutation(n) + 1
    grid = np.empty((n, n), dtype=np.int64)
    for i, r in enumerate(rows_order):
        for j, c in enumerate(cols_order):
            grid[i, j] = labels[pattern(r, c)]
    if rng.random() < 0.5:
        grid = grid.T.copy()
    return grid


def _random_backtracking_solution(box: int, rng: np.random.Generator) -> np.ndarray:
    """Fill an empty grid using randomized MRV/backtracking."""
    n = grid_size(box)
    full = (1 << n) - 1
    grid = np.zeros((n, n), dtype=np.int64)
    rows = [0] * n; cols = [0] * n; boxes = [0] * n
    empties = list(range(n * n))

    def backtrack() -> bool:
        if not empties:
            return True
        best_n = n + 1
        tied: list[tuple[int, int, int]] = []
        for idx, cell in enumerate(empties):
            r, c = divmod(cell, n)
            b = (r // box) * box + (c // box)
            avail = full & ~(rows[r] | cols[c] | boxes[b])
            pc = avail.bit_count()
            if pc < best_n:
                best_n, tied = pc, [(idx, cell, avail)]
            elif pc == best_n:
                tied.append((idx, cell, avail))
        if best_n == 0:
            return False
        best_i, cell, mask = tied[int(rng.integers(len(tied)))]
        empties.pop(best_i)
        r, c = divmod(cell, n)
        b = (r // box) * box + (c // box)
        bits: list[int] = []
        while mask:
            bit = mask & -mask
            mask ^= bit
            bits.append(bit)
        rng.shuffle(bits)
        for bit in bits:
            rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit
            grid[r, c] = bit.bit_length()
            if backtrack():
                return True
            rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit
        grid[r, c] = 0
        empties.insert(best_i, cell)
        return False

    if not backtrack():
        raise RuntimeError("randomized Sudoku completion unexpectedly failed")
    return grid


def generate_solution(
    box: int, rng: np.random.Generator, method: str = "random_backtracking"
) -> np.ndarray:
    """Generate a valid completed board using the declared construction method."""
    if method == "random_backtracking":
        grid = _random_backtracking_solution(box, rng)
    elif method == "canonical_symmetry":
        grid = _canonical_symmetry_solution(box, rng)
    else:
        raise ValueError(f"unknown Sudoku solution_method: {method!r}")
    if not is_solved(grid, box):
        raise RuntimeError("Sudoku generator produced an invalid completed grid")
    return grid


def make_puzzle(
    solution: np.ndarray,
    box: int,
    num_clues: int,
    rng: np.random.Generator,
    require_unique: bool = True,
) -> np.ndarray:
    n = grid_size(box)
    if not is_solved(solution, box):
        raise ValueError("solution must be a valid completed Sudoku grid")
    if not isinstance(num_clues, (int, np.integer)) or not 0 <= int(num_clues) <= n * n:
        raise ValueError(f"num_clues must be in [0, {n*n}]")
    puzzle = np.asarray(solution, dtype=np.int64).copy()
    cells = list(rng.permutation(n * n))
    target_blanks = n * n - int(num_clues)
    blanks = 0
    for cell in cells:
        if blanks >= target_blanks:
            break
        r, c = divmod(int(cell), n)
        saved = puzzle[r, c]
        puzzle[r, c] = 0
        if require_unique and count_solutions(puzzle, box, limit=2) != 1:
            puzzle[r, c] = saved
        else:
            blanks += 1
    if not is_valid_grid(puzzle, box):
        raise RuntimeError("Sudoku puzzle maker produced an invalid puzzle")
    return puzzle


def generate_pair(
    box: int,
    num_clues: int,
    rng: np.random.Generator,
    require_unique: bool = True,
    solution_method: str = "random_backtracking",
) -> tuple[np.ndarray, np.ndarray]:
    solution = generate_solution(box, rng, method=solution_method)
    puzzle = make_puzzle(solution, box, num_clues, rng, require_unique=require_unique)
    return puzzle, solution
